name: EST Tests

on: [push, pull_request]

jobs:
  build:
    name: Waiting for build
    uses: ./.github/workflows/wait-for-build.yml
    secrets: inherit

  est-basic-test:
    name: Basic EST
    needs: build
    uses: ./.github/workflows/est-basic-test.yml
          
  est-ds-realm-test:
    name: EST with ds realm
    needs: build
    uses: ./.github/workflows/est-ds-realm-test.yml

  est-postgresql-realm-test:
    name: EST with postgresql realm
    needs: build
    uses: ./.github/workflows/est-postgresql-realm-test.yml

  est-ds-realm-separate-test:
    name: EST with ds realm on a separate instance
    needs: build
    uses: ./.github/workflows/est-ds-realm-separate-test.yml

  est-standalone-test:
    name: EST on standalone instance with provided certificates
    needs: build
    uses: ./.github/workflows/est-standalone-test.yml
