name: IPA Tests

on: [push, pull_request]

jobs:
  # docs/development/Building_PKI.md
  build:
    name: Building PKI
    runs-on: ubuntu-latest
    container: registry.fedoraproject.org/fedora:${{ matrix.os }}
    strategy:
      matrix:
        os: ['32', '33']
    steps:
      - name: Install git
        run: dnf install -y git

      - name: Clone the repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          dnf install -y dnf-plugins-core rpm-build
          dnf copr enable -y @pki/master
          dnf builddep -y --allowerasing --spec ./pki.spec

      - name: Build PKI packages
        run: ./build.sh --with-pkgs=base,server,acme,ca,kra --with-timestamp --with-commit-id --work-dir=build rpm

      - name: Upload PKI packages
        uses: actions/upload-artifact@v2
        with:
          name: pki-build-${{ matrix.os }}
          path: build/RPMS/

  ipa-tests:
    name: Testing IPA
    needs: build
    runs-on: ubuntu-latest
    env:
      BUILDDIR: /tmp/workdir
      PKIDIR: /tmp/workdir/pki
      LOGS: ${GITHUB_WORKSPACE}/logs.txt
      COPR_REPO: "@pki/master"
      test_set: "test_caacl_plugin.py test_caacl_profile_enforcement.py test_cert_plugin.py test_certprofile_plugin.py test_ca_plugin.py test_vault_plugin.py"
    strategy:
      matrix:
        os: ['32', '33']
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Download PKI packages
        uses: actions/download-artifact@v2
        with:
          name: pki-build-${{ matrix.os }}
          path: build/RPMS

      - name: Build container image with systemd
        run: docker build ci -t ipa --build-arg OS_VERSION=${{ matrix.os }}

      - name: Run container
        run: |
          IMAGE=ipa \
          NAME=ipa \
          HOSTNAME=ipa.example.com \
          ci/runner-init.sh

      - name: Install dependencies
        run: |
          docker exec ipa dnf install -y findutils dnf-plugins-core
          docker exec ipa dnf copr enable -y @freeipa/freeipa-master-nightly
          docker exec ipa dnf copr enable -y ${COPR_REPO}

      - name: Install IPA packages
        run: docker exec ipa dnf install -y freeipa-server freeipa-server-dns freeipa-server-trust-ad python3-ipatests freeipa-healthcheck

      - name: Install PKI packages
        run: docker exec ipa bash -c "dnf -y localinstall ${PKIDIR}/build/RPMS/*"

      - name: Run IPA tests
        run: docker exec ipa ${PKIDIR}/ci/ipa-test.sh

      - name: Gather log files
        if: always()
        run: |
          docker exec ipa bash -c "journalctl -u pki-tomcatd@pki-tomcat > /var/log/pki/pki-journalctl.log"
          docker exec ipa bash -c "tar cvf ${PKIDIR}/ipa-logs.tar /var/log/ipa* /var/log/pki*"

      - name: Upload log files
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ipa-logs-${{ matrix.os }}
          path: ipa-logs.tar
