name: Tools Tests

on: [push, pull_request]

jobs:
  init:
    name: Initialization
    uses: ./.github/workflows/init.yml
    secrets: inherit

  build:
    name: Waiting for build
    needs: init
    uses: ./.github/workflows/wait-for-build.yml
    secrets: inherit

  PKICertImport-test:
    name: PKICertImport
    needs: [init, build]
    uses: ./.github/workflows/PKICertImport-test.yml

  pki-nss-rsa-test:
    name: PKI NSS CLI with RSA
    needs: [init, build]
    uses: ./.github/workflows/pki-nss-rsa-test.yml

  pki-nss-ecc-test:
    name: PKI NSS CLI with ECC
    needs: [init, build]
    uses: ./.github/workflows/pki-nss-ecc-test.yml

  pki-nss-aes-test:
    name: PKI NSS CLI with AES
    needs: [init, build]
    uses: ./.github/workflows/pki-nss-aes-test.yml

  pki-nss-hsm-test:
    name: PKI NSS CLI with HSM
    needs: [init, build]
    uses: ./.github/workflows/pki-nss-hsm-test.yml

  pki-nss-exts-test:
    name: PKI NSS CLI with Extensions
    needs: [init, build]
    uses: ./.github/workflows/pki-nss-exts-test.yml

  pki-pkcs7-test:
    name: PKI PKCS7 CLI
    needs: [init, build]
    uses: ./.github/workflows/pki-pkcs7-test.yml

  pki-pkcs11-test:
    name: PKI PKCS11 CLI
    needs: [init, build]
    uses: ./.github/workflows/pki-pkcs11-test.yml

  pki-pkcs12-test:
    name: PKI PKCS12 CLI
    needs: [init, build]
    uses: ./.github/workflows/pki-pkcs12-test.yml

  rpminspect-test:
    name: rpminspect
    needs: [init, build]
    uses: ./.github/workflows/rpminspect-test.yml

  update-version-test:
    name: Update Version
    uses: ./.github/workflows/update-version-test.yml
